### PR TITLE
Empty appointments bug fix

### LINKED ISSUE #151: Add check for empty data set in API, instead of cryptic error
Currently when the input data is empty the API will give 500 with a key-error on a column that does not exist. It would be better to raise a informative exception when the input is empty

### PR DESCRIPTION
**Pull request by WoltersEric**
closes #151

### CODE REVIEW

File: deploy.sh [hunk 1]
```diff
@@ -6,6 +6,8 @@ do
     fi
 done
 
+export SSL_CERT_FILE=/etc/ssl/certs/ca-bundle.crt
```
Comment (rubenpeters91) [inline deploy.sh:9]: Maybe add a comment why this is neccessary and add to CHANGELOG

File: src/noshow/api/app.py [hunk 2]
```diff
@@ -119,10 +119,18 @@ async def predict(
     project_path = Path(__file__).parents[3]
     start_time = datetime.now()
 
+    if len(input) == 0:
+        logger.error("No appointments provided")
```
Comment (rubenpeters91) [inline src/noshow/api/app.py:123]: I think the cleaner option would be to raise an exception, because generally we want to be informed when the appointment list is empty, this is only expected a couple of times per year. For example:
```raise HTTPException(status_code=400, detail="Input cannot be empty.")```
 maybe best to do both logger.error and the exception

**Review by rubenpeters91 — CHANGES_REQUESTED** [review]

**Comment by WoltersEric** [comment]
I added your suggestions. The latest version is now running on acceptance

File: src/noshow/api/app_helpers.py [hunk 3]
```diff
@@ -186,3 +186,93 @@ def create_treatment_groups(
...
     predictions["treatment_group"] = predictions["treatment_group"].astype(int)
     return predictions
+
+
+def store_predictions(
+    prediction_df: pd.DataFrame,
+    db: Session,
+    logger: Any,
+    apirequest: Any,
+    CLINIC_CONFIG: Dict[str, Any],
```
Comment (rubenpeters91) [inline src/noshow/api/app_helpers.py:196]: Maybe just import this from the config module? Saves another parameter

File: src/noshow/api/app_helpers.py [hunk 4]
```diff
@@ -186,3 +186,93 @@ def create_treatment_groups(
     predictions = predictions.drop(columns="score_bin")
     predictions["treatment_group"] = predictions["treatment_group"].astype(int)
     return predictions
+
+
+def store_predictions(
+    prediction_df: pd.DataFrame,
+    db: Session,
+    logger: Any,
```
Comment (rubenpeters91) [inline src/noshow/api/app_helpers.py:194]: Better to create a new logger object in this module and use that

File: src/noshow/api/app_helpers.py [hunk 5]
```diff
@@ -186,3 +186,93 @@ def create_treatment_groups(
...
+    apirequest: Any,
```
Comment (rubenpeters91) [inline src/noshow/api/app_helpers.py:195]: Type is ApiRequest

**Review by rubenpeters91 — CHANGES_REQUESTED** [review]

**Review by rubenpeters91 — APPROVED** [review]
Looks good, I think you need to change the monkeypatch for CLINIC_CONFIG, since it's also imported in app_helpers not only in app. That should fix the unit test
